### ISSUE TITLE
what the point of "> *"?

### ISSUE THREAD

**Issue by olhapi** [flexiblegs/flexiblegs-bem#1]
_Just want to know_

**Comment by dnomak** [comment]
``` scss
$breakpoint: (
  xl : "",
  lg : "(max-width: 1024px)",
  md : "(max-width: 768px)",
  sm : "(max-width: 667px)"
);
```

Is that what you asked ?

**Comment by olhapi** [comment]
I'm talking about that 
`.wrap > * {
  display: inline-block;
  }`
Maybe I just don't know something about this CSS feature, but I didn't see any reson to use this. Can you explain or just post a link to some article?

**Comment by dnomak** [comment]
Sorry for the late response.

This col is a feature. "float: left;" is used instead. It is required for responsive.

Please check through a compiled view.
http://flexible.gs/learn/wrap/?framework=bem#wrap-bem (normal wrap)
http://flexible.gs/learn/table/?framework=bem#table-bem (table wrap)
http://flexible.gs/learn/flexbox/?framework=bem#flexbox-bem (flexbox wrap)

**Comment by olhapi** [comment]
Thank you for the response. It seems clearly now.
